layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: false
    projects:
    - suyashjoshi.github.io

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  linkedin: suyashj
  # medium: @your_username
  stackoverflow: suyashjoshi
  # telegram: your_username
  twitter: suyashcjoshi
  # youtube: your_username
  # instagram: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url

topics:
  - name: Computational Creativity
    web_url: https://en.wikipedia.org/wiki/Computational_creativity
    image_url: https://i.imgur.com/l78hXsRs.png

  - name: STEAM Education
    web_url: https://en.wikipedia.org/wiki/STEAM_fields
    image_url: 

  - name: Magic and Juggling
    web_url: https://www.instagram.com/techillusionist/
    image_url: https://i.imgur.com/552cUWRs.png
